services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qrcode_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d qrcode_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: backend/Dockerfile.migrate
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://user:password@db:5432/qrcode_db?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    command: up

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://user:password@db:5432/qrcode_db?sslmode=disable
      GRPC_SERVER_ADDRESS: :9000
      JWT_SECRET: super_secret_jwt_key
      IPINFO_TOKEN: cf8fbbbc51fafc
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    expose:
      - "9000"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      GRPC_TARGET: backend:9000
      JWT_SECRET: super_secret_jwt_key
      APP_BASE_URL: http://localhost:8080
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - gateway

volumes:
  postgres_data: