services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    image: qrcode-backend:latest
    container_name: qrcode-backend
    environment:
      - PORT=8080
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "/app/server", "-h"]
      interval: 10s
      timeout: 2s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    image: qrcode-frontend:latest
    container_name: qrcode-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
