// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: qrcodegen/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Link struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalUrl      string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	Hash             string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TransitionsCount int64                  `protobuf:"varint,6,opt,name=transitions_count,json=transitionsCount,proto3" json:"transitions_count,omitempty"`
	Color            string                 `protobuf:"bytes,7,opt,name=color,proto3" json:"color,omitempty"`
	Background       string                 `protobuf:"bytes,8,opt,name=background,proto3" json:"background,omitempty"`
	Smoothing        float64                `protobuf:"fixed64,9,opt,name=smoothing,proto3" json:"smoothing,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Link) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *Link) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Link) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Link) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Link) GetTransitionsCount() int64 {
	if x != nil {
		return x.TransitionsCount
	}
	return 0
}

func (x *Link) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Link) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *Link) GetSmoothing() float64 {
	if x != nil {
		return x.Smoothing
	}
	return 0
}

type Transition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Referer       string                 `protobuf:"bytes,4,opt,name=referer,proto3" json:"referer,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Browser       string                 `protobuf:"bytes,6,opt,name=browser,proto3" json:"browser,omitempty"`
	Os            string                 `protobuf:"bytes,7,opt,name=os,proto3" json:"os,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transition) Reset() {
	*x = Transition{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transition) ProtoMessage() {}

func (x *Transition) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transition.ProtoReflect.Descriptor instead.
func (*Transition) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *Transition) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transition) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Transition) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Transition) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *Transition) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Transition) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *Transition) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Transition) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLinkRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRequest.ProtoReflect.Descriptor instead.
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetLinkRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetLinkRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type EditLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Background    string                 `protobuf:"bytes,5,opt,name=background,proto3" json:"background,omitempty"`
	Smoothing     float64                `protobuf:"fixed64,6,opt,name=smoothing,proto3" json:"smoothing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditLinkRequest) Reset() {
	*x = EditLinkRequest{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditLinkRequest) ProtoMessage() {}

func (x *EditLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditLinkRequest.ProtoReflect.Descriptor instead.
func (*EditLinkRequest) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *EditLinkRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditLinkRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EditLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *EditLinkRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *EditLinkRequest) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *EditLinkRequest) GetSmoothing() float64 {
	if x != nil {
		return x.Smoothing
	}
	return 0
}

type DeleteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkRequest) Reset() {
	*x = DeleteLinkRequest{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkRequest) ProtoMessage() {}

func (x *DeleteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLinkRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteLinkRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListLinksRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListLinksRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListLinksRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListLinksRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*Link                `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListLinksResponse) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

type GenerateQRCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Background    string                 `protobuf:"bytes,3,opt,name=background,proto3" json:"background,omitempty"`
	Smoothing     float64                `protobuf:"fixed64,4,opt,name=smoothing,proto3" json:"smoothing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQRCodeRequest) Reset() {
	*x = GenerateQRCodeRequest{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRCodeRequest) ProtoMessage() {}

func (x *GenerateQRCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateQRCodeRequest) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateQRCodeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GenerateQRCodeRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *GenerateQRCodeRequest) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *GenerateQRCodeRequest) GetSmoothing() float64 {
	if x != nil {
		return x.Smoothing
	}
	return 0
}

type GenerateQRCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQRCodeResponse) Reset() {
	*x = GenerateQRCodeResponse{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRCodeResponse) ProtoMessage() {}

func (x *GenerateQRCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRCodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateQRCodeResponse) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateQRCodeResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type GetRedirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Referer       string                 `protobuf:"bytes,4,opt,name=referer,proto3" json:"referer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedirectRequest) Reset() {
	*x = GetRedirectRequest{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedirectRequest) ProtoMessage() {}

func (x *GetRedirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedirectRequest.ProtoReflect.Descriptor instead.
func (*GetRedirectRequest) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetRedirectRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetRedirectRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GetRedirectRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *GetRedirectRequest) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

type GetRedirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedirectResponse) Reset() {
	*x = GetRedirectResponse{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedirectResponse) ProtoMessage() {}

func (x *GetRedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedirectResponse.ProtoReflect.Descriptor instead.
func (*GetRedirectResponse) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetRedirectResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetTransitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        int64                  `protobuf:"varint,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransitionsRequest) Reset() {
	*x = GetTransitionsRequest{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransitionsRequest) ProtoMessage() {}

func (x *GetTransitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransitionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransitionsRequest) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetTransitionsRequest) GetLinkId() int64 {
	if x != nil {
		return x.LinkId
	}
	return 0
}

func (x *GetTransitionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetTransitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transitions   []*Transition          `protobuf:"bytes,1,rep,name=transitions,proto3" json:"transitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransitionsResponse) Reset() {
	*x = GetTransitionsResponse{}
	mi := &file_qrcodegen_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransitionsResponse) ProtoMessage() {}

func (x *GetTransitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qrcodegen_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransitionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransitionsResponse) Descriptor() ([]byte, []int) {
	return file_qrcodegen_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetTransitionsResponse) GetTransitions() []*Transition {
	if x != nil {
		return x.Transitions
	}
	return nil
}

var File_qrcodegen_v1_service_proto protoreflect.FileDescriptor

const file_qrcodegen_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1aqrcodegen/v1/service.proto\x12\fqrcodegen.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"@\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x9d\x02\n" +
	"\x04Link\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12+\n" +
	"\x11transitions_count\x18\x06 \x01(\x03R\x10transitionsCount\x12\x14\n" +
	"\x05color\x18\a \x01(\tR\x05color\x12\x1e\n" +
	"\n" +
	"background\x18\b \x01(\tR\n" +
	"background\x12\x1c\n" +
	"\tsmoothing\x18\t \x01(\x01R\tsmoothing\"\xe8\x01\n" +
	"\n" +
	"Transition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x18\n" +
	"\areferer\x18\x04 \x01(\tR\areferer\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x18\n" +
	"\abrowser\x18\x06 \x01(\tR\abrowser\x12\x0e\n" +
	"\x02os\x18\a \x01(\tR\x02os\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"W\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"c\n" +
	"\x11CreateLinkRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"9\n" +
	"\x0eGetLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xb1\x01\n" +
	"\x0fEditLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\foriginal_url\x18\x03 \x01(\tR\voriginalUrl\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x1e\n" +
	"\n" +
	"background\x18\x05 \x01(\tR\n" +
	"background\x12\x1c\n" +
	"\tsmoothing\x18\x06 \x01(\x01R\tsmoothing\"<\n" +
	"\x11DeleteLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"r\n" +
	"\x10ListLinksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x14\n" +
	"\x05order\x18\x04 \x01(\tR\x05order\"=\n" +
	"\x11ListLinksResponse\x12(\n" +
	"\x05links\x18\x01 \x03(\v2\x12.qrcodegen.v1.LinkR\x05links\"}\n" +
	"\x15GenerateQRCodeRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12\x1e\n" +
	"\n" +
	"background\x18\x03 \x01(\tR\n" +
	"background\x12\x1c\n" +
	"\tsmoothing\x18\x04 \x01(\x01R\tsmoothing\".\n" +
	"\x16GenerateQRCodeResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"q\n" +
	"\x12GetRedirectRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x18\n" +
	"\areferer\x18\x04 \x01(\tR\areferer\"8\n" +
	"\x13GetRedirectResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"I\n" +
	"\x15GetTransitionsRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\x03R\x06linkId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"T\n" +
	"\x16GetTransitionsResponse\x12:\n" +
	"\vtransitions\x18\x01 \x03(\v2\x18.qrcodegen.v1.TransitionR\vtransitions2\xf8\x05\n" +
	"\rQRCodeService\x12A\n" +
	"\bRegister\x12\x1d.qrcodegen.v1.RegisterRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x05Login\x12\x1a.qrcodegen.v1.LoginRequest\x1a\x1b.qrcodegen.v1.LoginResponse\x12A\n" +
	"\n" +
	"CreateLink\x12\x1f.qrcodegen.v1.CreateLinkRequest\x1a\x12.qrcodegen.v1.Link\x12N\n" +
	"\vGetAllLinks\x12\x1e.qrcodegen.v1.ListLinksRequest\x1a\x1f.qrcodegen.v1.ListLinksResponse\x12;\n" +
	"\aGetLink\x12\x1c.qrcodegen.v1.GetLinkRequest\x1a\x12.qrcodegen.v1.Link\x12=\n" +
	"\bEditLink\x12\x1d.qrcodegen.v1.EditLinkRequest\x1a\x12.qrcodegen.v1.Link\x12E\n" +
	"\n" +
	"DeleteLink\x12\x1f.qrcodegen.v1.DeleteLinkRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\x0eGetTransitions\x12#.qrcodegen.v1.GetTransitionsRequest\x1a$.qrcodegen.v1.GetTransitionsResponse\x12[\n" +
	"\x0eGenerateQRCode\x12#.qrcodegen.v1.GenerateQRCodeRequest\x1a$.qrcodegen.v1.GenerateQRCodeResponse\x12R\n" +
	"\vGetRedirect\x12 .qrcodegen.v1.GetRedirectRequest\x1a!.qrcodegen.v1.GetRedirectResponseB\x19Z\x17qrcodegen/pkg/api/v1;v1b\x06proto3"

var (
	file_qrcodegen_v1_service_proto_rawDescOnce sync.Once
	file_qrcodegen_v1_service_proto_rawDescData []byte
)

func file_qrcodegen_v1_service_proto_rawDescGZIP() []byte {
	file_qrcodegen_v1_service_proto_rawDescOnce.Do(func() {
		file_qrcodegen_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qrcodegen_v1_service_proto_rawDesc), len(file_qrcodegen_v1_service_proto_rawDesc)))
	})
	return file_qrcodegen_v1_service_proto_rawDescData
}

var file_qrcodegen_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_qrcodegen_v1_service_proto_goTypes = []any{
	(*User)(nil),                   // 0: qrcodegen.v1.User
	(*Link)(nil),                   // 1: qrcodegen.v1.Link
	(*Transition)(nil),             // 2: qrcodegen.v1.Transition
	(*RegisterRequest)(nil),        // 3: qrcodegen.v1.RegisterRequest
	(*LoginRequest)(nil),           // 4: qrcodegen.v1.LoginRequest
	(*LoginResponse)(nil),          // 5: qrcodegen.v1.LoginResponse
	(*CreateLinkRequest)(nil),      // 6: qrcodegen.v1.CreateLinkRequest
	(*GetLinkRequest)(nil),         // 7: qrcodegen.v1.GetLinkRequest
	(*EditLinkRequest)(nil),        // 8: qrcodegen.v1.EditLinkRequest
	(*DeleteLinkRequest)(nil),      // 9: qrcodegen.v1.DeleteLinkRequest
	(*ListLinksRequest)(nil),       // 10: qrcodegen.v1.ListLinksRequest
	(*ListLinksResponse)(nil),      // 11: qrcodegen.v1.ListLinksResponse
	(*GenerateQRCodeRequest)(nil),  // 12: qrcodegen.v1.GenerateQRCodeRequest
	(*GenerateQRCodeResponse)(nil), // 13: qrcodegen.v1.GenerateQRCodeResponse
	(*GetRedirectRequest)(nil),     // 14: qrcodegen.v1.GetRedirectRequest
	(*GetRedirectResponse)(nil),    // 15: qrcodegen.v1.GetRedirectResponse
	(*GetTransitionsRequest)(nil),  // 16: qrcodegen.v1.GetTransitionsRequest
	(*GetTransitionsResponse)(nil), // 17: qrcodegen.v1.GetTransitionsResponse
	(*timestamppb.Timestamp)(nil),  // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 19: google.protobuf.Empty
}
var file_qrcodegen_v1_service_proto_depIdxs = []int32{
	18, // 0: qrcodegen.v1.Link.created_at:type_name -> google.protobuf.Timestamp
	18, // 1: qrcodegen.v1.Transition.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: qrcodegen.v1.ListLinksResponse.links:type_name -> qrcodegen.v1.Link
	2,  // 3: qrcodegen.v1.GetTransitionsResponse.transitions:type_name -> qrcodegen.v1.Transition
	3,  // 4: qrcodegen.v1.QRCodeService.Register:input_type -> qrcodegen.v1.RegisterRequest
	4,  // 5: qrcodegen.v1.QRCodeService.Login:input_type -> qrcodegen.v1.LoginRequest
	6,  // 6: qrcodegen.v1.QRCodeService.CreateLink:input_type -> qrcodegen.v1.CreateLinkRequest
	10, // 7: qrcodegen.v1.QRCodeService.GetAllLinks:input_type -> qrcodegen.v1.ListLinksRequest
	7,  // 8: qrcodegen.v1.QRCodeService.GetLink:input_type -> qrcodegen.v1.GetLinkRequest
	8,  // 9: qrcodegen.v1.QRCodeService.EditLink:input_type -> qrcodegen.v1.EditLinkRequest
	9,  // 10: qrcodegen.v1.QRCodeService.DeleteLink:input_type -> qrcodegen.v1.DeleteLinkRequest
	16, // 11: qrcodegen.v1.QRCodeService.GetTransitions:input_type -> qrcodegen.v1.GetTransitionsRequest
	12, // 12: qrcodegen.v1.QRCodeService.GenerateQRCode:input_type -> qrcodegen.v1.GenerateQRCodeRequest
	14, // 13: qrcodegen.v1.QRCodeService.GetRedirect:input_type -> qrcodegen.v1.GetRedirectRequest
	19, // 14: qrcodegen.v1.QRCodeService.Register:output_type -> google.protobuf.Empty
	5,  // 15: qrcodegen.v1.QRCodeService.Login:output_type -> qrcodegen.v1.LoginResponse
	1,  // 16: qrcodegen.v1.QRCodeService.CreateLink:output_type -> qrcodegen.v1.Link
	11, // 17: qrcodegen.v1.QRCodeService.GetAllLinks:output_type -> qrcodegen.v1.ListLinksResponse
	1,  // 18: qrcodegen.v1.QRCodeService.GetLink:output_type -> qrcodegen.v1.Link
	1,  // 19: qrcodegen.v1.QRCodeService.EditLink:output_type -> qrcodegen.v1.Link
	19, // 20: qrcodegen.v1.QRCodeService.DeleteLink:output_type -> google.protobuf.Empty
	17, // 21: qrcodegen.v1.QRCodeService.GetTransitions:output_type -> qrcodegen.v1.GetTransitionsResponse
	13, // 22: qrcodegen.v1.QRCodeService.GenerateQRCode:output_type -> qrcodegen.v1.GenerateQRCodeResponse
	15, // 23: qrcodegen.v1.QRCodeService.GetRedirect:output_type -> qrcodegen.v1.GetRedirectResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_qrcodegen_v1_service_proto_init() }
func file_qrcodegen_v1_service_proto_init() {
	if File_qrcodegen_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qrcodegen_v1_service_proto_rawDesc), len(file_qrcodegen_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qrcodegen_v1_service_proto_goTypes,
		DependencyIndexes: file_qrcodegen_v1_service_proto_depIdxs,
		MessageInfos:      file_qrcodegen_v1_service_proto_msgTypes,
	}.Build()
	File_qrcodegen_v1_service_proto = out.File
	file_qrcodegen_v1_service_proto_goTypes = nil
	file_qrcodegen_v1_service_proto_depIdxs = nil
}
