// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: qrcodegen/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QRCodeService_Register_FullMethodName       = "/qrcodegen.v1.QRCodeService/Register"
	QRCodeService_Login_FullMethodName          = "/qrcodegen.v1.QRCodeService/Login"
	QRCodeService_CreateLink_FullMethodName     = "/qrcodegen.v1.QRCodeService/CreateLink"
	QRCodeService_GetAllLinks_FullMethodName    = "/qrcodegen.v1.QRCodeService/GetAllLinks"
	QRCodeService_GetLink_FullMethodName        = "/qrcodegen.v1.QRCodeService/GetLink"
	QRCodeService_EditLink_FullMethodName       = "/qrcodegen.v1.QRCodeService/EditLink"
	QRCodeService_DeleteLink_FullMethodName     = "/qrcodegen.v1.QRCodeService/DeleteLink"
	QRCodeService_GetTransitions_FullMethodName = "/qrcodegen.v1.QRCodeService/GetTransitions"
	QRCodeService_GenerateQRCode_FullMethodName = "/qrcodegen.v1.QRCodeService/GenerateQRCode"
	QRCodeService_GetRedirect_FullMethodName    = "/qrcodegen.v1.QRCodeService/GetRedirect"
)

// QRCodeServiceClient is the client API for QRCodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QRCodeServiceClient interface {
	// Auth
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Links
	CreateLink(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*Link, error)
	GetAllLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error)
	GetLink(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*Link, error)
	EditLink(ctx context.Context, in *EditLinkRequest, opts ...grpc.CallOption) (*Link, error)
	DeleteLink(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Analytics
	GetTransitions(ctx context.Context, in *GetTransitionsRequest, opts ...grpc.CallOption) (*GetTransitionsResponse, error)
	// Core Logic
	GenerateQRCode(ctx context.Context, in *GenerateQRCodeRequest, opts ...grpc.CallOption) (*GenerateQRCodeResponse, error)
	GetRedirect(ctx context.Context, in *GetRedirectRequest, opts ...grpc.CallOption) (*GetRedirectResponse, error)
}

type qRCodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQRCodeServiceClient(cc grpc.ClientConnInterface) QRCodeServiceClient {
	return &qRCodeServiceClient{cc}
}

func (c *qRCodeServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QRCodeService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qRCodeServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, QRCodeService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qRCodeServiceClient) CreateLink(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*Link, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Link)
	err := c.cc.Invoke(ctx, QRCodeService_CreateLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qRCodeServiceClient) GetAllLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinksResponse)
	err := c.cc.Invoke(ctx, QRCodeService_GetAllLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qRCodeServiceClient) GetLink(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*Link, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Link)
	err := c.cc.Invoke(ctx, QRCodeService_GetLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qRCodeServiceClient) EditLink(ctx context.Context, in *EditLinkRequest, opts ...grpc.CallOption) (*Link, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Link)
	err := c.cc.Invoke(ctx, QRCodeService_EditLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qRCodeServiceClient) DeleteLink(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QRCodeService_DeleteLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qRCodeServiceClient) GetTransitions(ctx context.Context, in *GetTransitionsRequest, opts ...grpc.CallOption) (*GetTransitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransitionsResponse)
	err := c.cc.Invoke(ctx, QRCodeService_GetTransitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qRCodeServiceClient) GenerateQRCode(ctx context.Context, in *GenerateQRCodeRequest, opts ...grpc.CallOption) (*GenerateQRCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateQRCodeResponse)
	err := c.cc.Invoke(ctx, QRCodeService_GenerateQRCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qRCodeServiceClient) GetRedirect(ctx context.Context, in *GetRedirectRequest, opts ...grpc.CallOption) (*GetRedirectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRedirectResponse)
	err := c.cc.Invoke(ctx, QRCodeService_GetRedirect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QRCodeServiceServer is the server API for QRCodeService service.
// All implementations must embed UnimplementedQRCodeServiceServer
// for forward compatibility.
type QRCodeServiceServer interface {
	// Auth
	Register(context.Context, *RegisterRequest) (*emptypb.Empty, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Links
	CreateLink(context.Context, *CreateLinkRequest) (*Link, error)
	GetAllLinks(context.Context, *ListLinksRequest) (*ListLinksResponse, error)
	GetLink(context.Context, *GetLinkRequest) (*Link, error)
	EditLink(context.Context, *EditLinkRequest) (*Link, error)
	DeleteLink(context.Context, *DeleteLinkRequest) (*emptypb.Empty, error)
	// Analytics
	GetTransitions(context.Context, *GetTransitionsRequest) (*GetTransitionsResponse, error)
	// Core Logic
	GenerateQRCode(context.Context, *GenerateQRCodeRequest) (*GenerateQRCodeResponse, error)
	GetRedirect(context.Context, *GetRedirectRequest) (*GetRedirectResponse, error)
	mustEmbedUnimplementedQRCodeServiceServer()
}

// UnimplementedQRCodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQRCodeServiceServer struct{}

func (UnimplementedQRCodeServiceServer) Register(context.Context, *RegisterRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedQRCodeServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedQRCodeServiceServer) CreateLink(context.Context, *CreateLinkRequest) (*Link, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLink not implemented")
}
func (UnimplementedQRCodeServiceServer) GetAllLinks(context.Context, *ListLinksRequest) (*ListLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllLinks not implemented")
}
func (UnimplementedQRCodeServiceServer) GetLink(context.Context, *GetLinkRequest) (*Link, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLink not implemented")
}
func (UnimplementedQRCodeServiceServer) EditLink(context.Context, *EditLinkRequest) (*Link, error) {
	return nil, status.Error(codes.Unimplemented, "method EditLink not implemented")
}
func (UnimplementedQRCodeServiceServer) DeleteLink(context.Context, *DeleteLinkRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLink not implemented")
}
func (UnimplementedQRCodeServiceServer) GetTransitions(context.Context, *GetTransitionsRequest) (*GetTransitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransitions not implemented")
}
func (UnimplementedQRCodeServiceServer) GenerateQRCode(context.Context, *GenerateQRCodeRequest) (*GenerateQRCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateQRCode not implemented")
}
func (UnimplementedQRCodeServiceServer) GetRedirect(context.Context, *GetRedirectRequest) (*GetRedirectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRedirect not implemented")
}
func (UnimplementedQRCodeServiceServer) mustEmbedUnimplementedQRCodeServiceServer() {}
func (UnimplementedQRCodeServiceServer) testEmbeddedByValue()                       {}

// UnsafeQRCodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QRCodeServiceServer will
// result in compilation errors.
type UnsafeQRCodeServiceServer interface {
	mustEmbedUnimplementedQRCodeServiceServer()
}

func RegisterQRCodeServiceServer(s grpc.ServiceRegistrar, srv QRCodeServiceServer) {
	// If the following call panics, it indicates UnimplementedQRCodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QRCodeService_ServiceDesc, srv)
}

func _QRCodeService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QRCodeService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QRCodeService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QRCodeService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QRCodeService_CreateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).CreateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QRCodeService_CreateLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).CreateLink(ctx, req.(*CreateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QRCodeService_GetAllLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).GetAllLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QRCodeService_GetAllLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).GetAllLinks(ctx, req.(*ListLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QRCodeService_GetLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).GetLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QRCodeService_GetLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).GetLink(ctx, req.(*GetLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QRCodeService_EditLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).EditLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QRCodeService_EditLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).EditLink(ctx, req.(*EditLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QRCodeService_DeleteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).DeleteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QRCodeService_DeleteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).DeleteLink(ctx, req.(*DeleteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QRCodeService_GetTransitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).GetTransitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QRCodeService_GetTransitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).GetTransitions(ctx, req.(*GetTransitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QRCodeService_GenerateQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQRCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).GenerateQRCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QRCodeService_GenerateQRCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).GenerateQRCode(ctx, req.(*GenerateQRCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QRCodeService_GetRedirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRedirectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).GetRedirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QRCodeService_GetRedirect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).GetRedirect(ctx, req.(*GetRedirectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QRCodeService_ServiceDesc is the grpc.ServiceDesc for QRCodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QRCodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qrcodegen.v1.QRCodeService",
	HandlerType: (*QRCodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _QRCodeService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _QRCodeService_Login_Handler,
		},
		{
			MethodName: "CreateLink",
			Handler:    _QRCodeService_CreateLink_Handler,
		},
		{
			MethodName: "GetAllLinks",
			Handler:    _QRCodeService_GetAllLinks_Handler,
		},
		{
			MethodName: "GetLink",
			Handler:    _QRCodeService_GetLink_Handler,
		},
		{
			MethodName: "EditLink",
			Handler:    _QRCodeService_EditLink_Handler,
		},
		{
			MethodName: "DeleteLink",
			Handler:    _QRCodeService_DeleteLink_Handler,
		},
		{
			MethodName: "GetTransitions",
			Handler:    _QRCodeService_GetTransitions_Handler,
		},
		{
			MethodName: "GenerateQRCode",
			Handler:    _QRCodeService_GenerateQRCode_Handler,
		},
		{
			MethodName: "GetRedirect",
			Handler:    _QRCodeService_GetRedirect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qrcodegen/v1/service.proto",
}
